apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-backend-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-backend
  template:
    metadata:
      labels:
        app: audio-backend
    spec:
      containers:
      - name: audio-backend-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-central1-docker.pkg.dev/athletics-hub/audio-backend-repo/audio-backend-gke@sha256:e98c607a3482a0d4693b9a23954d8f11d68332b346438fddc2a404f8df9d6a31
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            ephemeral-storage: "16Gi"
          limits:
            memory: "16Gi"
            cpu: "4"
            ephemeral-storage: "16Gi"