apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-backend-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-backend
  template:
    metadata:
      labels:
        app: audio-backend
    spec:
      containers:
      - name: audio-backend-app
        image: gcr.io/athletics-hub/github.com/colinfitzgerald328/audio-backend
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            ephemeral-storage: "16Gi"
          limits:
            memory: "8Gi"
            cpu: "2"
            ephemeral-storage: "16Gi"